### ISSUE TITLE
tox broken

### ISSUE THREAD

**Issue by jugmac00** [plone/plone.reload#14]
```
❯ tox -e py38
py38 create: /home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38
py38 installdeps: setuptools==33.1.1, zc.buildout
py38 installed: zc.buildout==2.13.3
py38 run-test-pre: PYTHONHASHSEED='3488596511'
py38 run-test: commands[0] | /home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/bin/buildout -c /home/jugmac00/All/output_plone/plone/plone.reload/buildout.cfg buildout:directory=/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38 buildout:develop=/home/jugmac00/All/output_plone/plone/plone.reload bootstrap
Creating directory '/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/eggs'.
Creating directory '/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/parts'.
Creating directory '/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/develop-eggs'.
Generated script '/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/bin/buildout'.
py38 run-test: commands[1] | /home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/bin/buildout -c /home/jugmac00/All/output_plone/plone/plone.reload/buildout.cfg buildout:directory=/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38 buildout:develop=/home/jugmac00/All/output_plone/plone/plone.reload
Develop: '/home/jugmac00/All/output_plone/plone/plone.reload'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Getting distribution for 'zc.recipe.testrunner==2.2'.
warning: no files found matching '*.bat' under directory 'docs'
warning: no files found matching '*.py' under directory 'docs'
warning: no files found matching '*.rst' under directory 'docs'
warning: no files found matching '*.txt' under directory 'docs'
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching '*.gif' under directory 'src'
warning: no files found matching '*.pt' under directory 'src'
warning: no files found matching '*.xml' under directory 'src'
warning: no files found matching '*.zcml' under directory 'src'
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-tuzo7fvd/zc.recipe.testrunner-2.2/setup.py", line 11, in <module>
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 2266, in main
    setup(
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 655, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    run_setup(setup_script, args)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-tuzo7fvd/zc.recipe.testrunner-2.2/setup.py", line 11, in <module>
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
An error occurred when trying to install /tmp/tmpadvkyzpnget_dist/zc.recipe.testrunner-2.2.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing.
  Getting section test.
  Initializing section test.
  Installing recipe zc.recipe.testrunner.
  Getting distribution for 'zc.recipe.testrunner==2.2'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 701, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 701, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1324, in __getitem__
    options._initialize()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1432, in _initialize
    self.initialize()
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1438, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1381, in _install_and_load
    zc.buildout.easy_install.install(
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 682, in install
    for dist in self._get_dist(requirement, ws):
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)
ERROR: InvocationError for command /home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38/bin/buildout -c buildout.cfg buildout:directory=/home/jugmac00/All/output_plone/plone/plone.reload/.tox/py38 buildout:develop=/home/jugmac00/All/output_plone/plone/plone.reload (exited with code 1)
_______________________________________________________________________________________ summary _______________________________________________________________________________________
ERROR:   py38: commands failed

```

I noticed this when I ran tox for all Zope/Plone repos this weekend, see https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/

I do not use this package, and unfortunately I do not have the time to investigate this bug.

**Comment by gforcada** [comment]
For a while it is using `plone.meta` and `tox` works fine :)
